var secondHeader =
  '   <div class="topBar">\n<div class="mobileHide">\n<div class="container-fluid">\n    <div class="row">\n        <div class="col-sm-12 col-md-4">\n            <a href="#!">InformArtistica</a>\n        </div>\n        <div class="col-sm-12 col-md-4">\n          <img src="./assets/img/logo.png" alt="logo" class="logo">\n      </div>\n      <div class="col-sm-12 col-md-4">\n        <a href="#!" class="logOut">Alessandra</a>\n    </div>\n    </div>\n</div>\n</div>\n<div class=\'mobileShow\'>\n<div class="container">\n    <div class="row">\n    <ul>    \n    <li class="logoWrapper">\n        <img src="./assets/img/logo.png" alt="logo" class="logo">\n        </li>\n        <li class="logOutWrapper">\n        <a href="#!">\n        <img src="../assets/img/logOut.svg" alt="LogOut" class="logOutMobile">\n        </a>\n        </li>\n        </ul>\n    </div>\n</div>\n</div>\n</div>\n\n';
var secondMain =
  ' <div class="content toggleable">\n<div class="container">\n    <div class="row">\n        <div class="col text-center">\n            <h1>Inform<span class="greenFont">A</span>rtistica</h1>\n            <div class="content-container">\n              <p class="paraTitle">Poche cose riescono a far emergere il meglio \n                di ognuno di noi come l\u2019arte.</p>\n                <p>Passione, ricerca e tecnica sono sempre all\u2019origine di ogni grande \n                  opera artistica e allo stesso modo guidano il nostro lavoro quotidiano \n                  per raggiungere ogni giorno traguardi sempre pi\xF9 ambiziosi.</p>\n                  <h5>TIRA FUORI L\u2019ARTISTA CHE C\u2019\xE8 IN TE!</h5>\n                  <button class="btnNext openThird">\n                    <img src="./assets/img/arrow-right.svg" alt="Next">\n                  </button>\n            </div>\n        </div>\n    </div>\n</div>\n</div>\n<script>\n$(document).ready(function(){\n  $(\'.openThird\').on(\'click\' ,function(){\n    $(\'body\').addClass(\'thirdBody\');\n    $(\'.toggleable\').animate({\'opacity\': 0}, 400, function(){\n      $(this).html(thirdMain).animate({\'opacity\': 1}, 400); \n      displayCounter(150, "#characterLeft");\n    });\n  });\n})</script>';
var thirdMain =
  '  <div class="content toggleable thirdScreen">\n<div class="container">\n  <div class="row">\n    <div class="col-lg-6 text-center">\n      <div class="leftBoxBackground"></div>\n      <div class="leftBox">\n        <p>\n          Se dovessi sceglierne uno, in quale artista ti <span class="bold">identificheresti</span> di pi\xF9, pensando\n          al suo modo di affrontare\n          la vita ed il lavoro?\n        </p>\n        <div>\n          <textarea id="comment" maxlength="150"></textarea>\n          <label id="characterLeft" class="thirdScreenCounter"></label>\n        </div>\n      </div>\n    </div>\n    <div class="col-lg-6 text-center">\n      <div class="rightBoxBackground"></div>\n      <div class="rightBox">\n        <p>\n          Condividi quella che\n          secondo te \xE8 la sua <span class="bold">opera</span>\n          pi\xF9 significativa\n        </p>\n        <input type="file">\n        <div>\n          <div class="uploadZone">\n            <p>Trascina qui il file da caricare oppure</p>\n            <img src="./assets/img/plus.svg" alt="plus sign">\n            <div class="uploadBtn">Carica contenuto</div>\n          </div>\n        </div>\n          <button class="btnNext"><img src="./assets/img/arrow-right.svg" alt="next"></button>\n      </div>\n    </div>\n  </div>\n</div>\n</div>\n<script>\n$(document).ready(function(){\n  $(\'.btnNext\').on(\'click\' ,function(){\n    console.log(123)\n    $(\'body\').removeClass(\'thirdBody\');\n    $(\'.toggleable\').animate({\'opacity\': 0}, 400, function(){\n      $(this).html(textScreen).animate({\'opacity\': 1}, 400); \n    });\n  });\n})</script>';
var textScreen =
  '\n<div class="content toggleable textScreen">\n    <div class="container">\n      <div class="row">\n        <div class="col-md-12 text-center">\n          <div class="leftBoxBackground"></div>\n          <div class="leftBox">\n            <p class="text-center">\n              Raccontaci con un <span class="bold">pensiero</span> o una <span class="bold">citazione</span> il \nperch\xE8 della tua scelta:\n            </p>\n            <div>\n              <textarea id="comment" maxlength="300"></textarea>\n              <label id="characterLeft"></label>\n            </div>\n            \n            <button class="btnNext"><img src="../assets/img/arrow-right.svg" alt="next"></button>\n          </div>\n        </div>\n       \n      </div>\n    </div>\n  </div>\n  <script>\n  $(document).ready(function(){\n  $(\'body\').addClass(\'sixth\');\n  displayCounter(300, "#characterLeft");\n  \n    $(\'.btnNext\').on(\'click\' ,function(){\n      console.log(123)\n      $(\'.toggleable\').animate({\'opacity\': 0}, 400, function(){\n        $(this).html(fourthMain).animate({\'opacity\': 1}, 400); \n      });\n      $(\'body\').addClass(\'sixth\');\n    });\n  })</script>';
var fourthMain =
  "<div class=\"content toggleable fifthScreen\">\n<div class=\"container\">\n  <div class=\"row\">\n    <div class=\"col-md-12 text-center\">\n      <h1>Ci vediamo \n        il 15 Settembre</h1>\n        <a href=\"#!\" class=\"btn-yellow\" id=\"btnNext\">Una sorpresa arriver\xE0 molto presto</a>\n    </div>\n    \n  </div>\n</div>\n</div>\n<script>\n$(document).ready(function(){\n$('body').addClass('sixth');\n\n  $('#btnNext').on('click' ,function(){\n    console.log(123)\n    $('.toggleable').animate({'opacity': 0}, 400, function(){\n      $(this).html(fifthMain).animate({'opacity': 1}, 400); \n    });\n    $('body').addClass('sixth');\n  });\n})</script>";
var fifthMain =
  '<div class="content toggleable sixthScreen">\n<div class="container">\n  <div class="row">\n    <div class="col text-center">\n      <div class="wrapper">\n      <h5>Troppo presto! </h5>\n      <p>Cliccami dal </p>\n      <h5>15 Settembre :) </h5>\n      <a href=\'/index.html\' class="btnNext">\n        <img src="../assets/img/arrow-right.svg" alt="Submit Button">\n      </a>\n      </div>\n    </div>\n  </div>\n</div>\n</div>\n';
